### ISSUE TITLE
Listar ferramentas necessárias para o projeto

### ISSUE THREAD

**Issue by l-gustavo-barbosa** [l-gustavo-barbosa/candagoScrum#9]
Listagem detalhada de sites, referências, linguagens de programação, frameworks, libs e aplicativos que serão usados no desenvolvimento e deploy do projeto.

**Comment by RafaelSM21** [comment]
- Linguagem: HTML e CSS

- Frameworks: Bootstrap e Semantic UI

- Referências: https://www.vestibularfatec.com.br/home/       https://scrumerdataapi.github.io/API/index.html       

- https://www.atlassian.com/agile

- Ferramentas usadas: Figma, VS Code e Git,
